### ISSUE TITLE
SDS anchoring by default turned off?

### ISSUE THREAD

**Issue by ChrisWu1997** [kylesargent/ZeroNVS#4]
Hi,

Is SDS anchoring by default turned off? I saw `n_aux_c2w = 0` in `zero123_scene.yaml`, which I guess means no anchor cameras. So if I run `launch_eval_mipnerf360.sh` directly, it's standard SDS without anchoring?

Thanks for the great work!

**Comment by kylesargent** [comment]
That's right. SDS anchoring is intended to improve diversity as measured by human preference in a user study. We leave it off for the view synthesis metrics.

**Comment by ChrisWu1997** [comment]
Thanks for the quick reply! 

I just tried running `bash launch_eval_mipnerf360.sh` without touching anything, but it doesn't seem to converge:

https://github.com/kylesargent/ZeroNVS/assets/32172140/4738daa1-c354-431e-bb16-abc4466d4a11

Is the config correct or am I missing anything?

**Comment by kylesargent** [comment]
Indeed this is not converged. Can you check your console for the message "SDS distillation only, disabling some functionality..."?

The reason is that this code branch needs to run in order to allow gradients to flow through the U-Net:
https://github.com/kylesargent/zeronvs_diffusion/blob/739073564a8d09ef3ce2317cae8ff75e22198077/zero123/ldm/models/diffusion/ddpm.py#L24 

It looks to me like the RGB loss is working here but the SDS loss is not, which might lead to the issues we see.

**Comment by ChrisWu1997** [comment]
Yeah, that fixed it. By default the repo is cloned to "ZeroNVS/zeronvs_diffusion", which does not match that condition.

Thanks a lot!
